set(SVM_VERSION "1.0.4")
set(SVM_VERSION_MAJOR "1")
set(SVM_VERSION_MINOR "0")
set(SVM_VERSION_PATCH "4")
set(SVM_VERSION_TWEAK "0")
set(SVM_RELEASE_TAG "v1.0.4")
set(SVM_PRODUCT_DISPLAY_NAME "串口值匹配器")
set(SVM_PRODUCT_REPOSITORY_NAME "SerialValueMatcher Native")
set(SVM_PRODUCT_AUTHOR "w")
set(SVM_PRODUCT_DESCRIPTION "面向中文用户的 Windows 原生串口调试、Modbus RTU 扫描和值候选分析工具")
set(SVM_WIN32_FILE_DESCRIPTION "串口值匹配器 Win32 Native")
set(SVM_WIN32_INTERNAL_NAME "svm-native-win32")
set(SVM_WIN32_EXE_NAME "svm-native-win32.exe")
set(SVM_PACKAGE_ARTIFACT "SerialValueMatcherNative-win32-native-x64")
set(SVM_MINGW_PACKAGE_ARTIFACT "SerialValueMatcherNative-win32-native-x64-mingw")
set(SVM_RELEASE_URL "https://github.com/D1654/serial-value-matcher-native/releases/tag/v1.0.4")
